### ISSUE TITLE
"fdroid/stats" failed: No such file or directory

### ISSUE THREAD

**Issue by grote** [wardvl/f-droid-nightly-action#2]
When trying to publish for the first time into an empty nightly repo, I get this error:
```
2021-11-23 19:59:30,932 DEBUG: rsync --recursive --safe-links --times --perms --one-file-system --delete --chmod=Da+rx,Fa-x,a+r,u+w --checksum --verbose /github/workspace/fdroid/stats/ /github/workspace/fdroid/git-mirror/fdroid/stats/
rsync: change_dir "/github/workspace/fdroid/stats" failed: No such file or directory (2)
sending incremental file list
created directory /github/workspace/fdroid/git-mirror/fdroid/stats
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]

sent 20 bytes  received 83 bytes  206.00 bytes/sec
total size is 0  speedup is 0.00
Traceback (most recent call last):
  File "/usr/local/bin/fdroid", line 4, in <module>
    __import__('pkg_resources').run_script('fdroidserver==2.1a0.dev0', 'fdroid')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/fdroidserver-2.1a0.dev0-py3.5.egg/EGG-INFO/scripts/fdroid", line 22, in <module>
    fdroidserver.__main__.main()
  File "/usr/local/lib/python3.5/dist-packages/fdroidserver-2.1a0.dev0-py3.5.egg/fdroidserver/__main__.py", line 208, in main
    mod.main()
  File "/usr/local/lib/python3.5/dist-packages/fdroidserver-2.1a0.dev0-py3.5.egg/fdroidserver/nightly.py", line 404, in main
    common.local_rsync(options, repo_basedir + '/stats/', git_mirror_statsdir + '/')
  File "/usr/local/lib/python3.5/dist-packages/fdroidserver-2.1a0.dev0-py3.5.egg/fdroidserver/common.py", line 3707, in local_rsync
    raise FDroidException()
fdroidserver.exception.FDroidException: fdroidserver.exception
```

**Comment by grote** [comment]
In case anybody else finds this: It happens when you don't build the app before. I had commented it out for debugging. When running something like `./gradlew assembleDebug` before, it works.
